"""First commit

Revision ID: 2d96bf95e88b
Revises: 
Create Date: 2023-11-07 23:54:39.922991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d96bf95e88b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('Macho', 'Hembra', name='sexenum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_id'), 'animal', ['id'], unique=False)
    op.create_index(op.f('ix_animal_name'), 'animal', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animal_name'), table_name='animal')
    op.drop_index(op.f('ix_animal_id'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###
